export const APP_NAMESPACE = "TRANSACTIONS";

export const SET_WEEKDAYS = `${APP_NAMESPACE}/SET_WEEKDAYS`;
export const TOGGLE_ITEM_EDITOR = `${APP_NAMESPACE}/TOGGLE_ITEM_EDITOR`;
export const ADD_TRANSACTION = `${APP_NAMESPACE}/ADD_TRANSACTION`;
export const EDIT_TRANSACTION = `${APP_NAMESPACE}/EDIT_TRANSACTION`;
export const REMOVE_TRANSACTION = `${APP_NAMESPACE}/REMOVE_TRANSACTION`;

export const CATEGORIES = ["Food", "Shopping", "Household", "Others"];
